# Introduction to Sklearn

I will  practice SkLearn and try to implement eistimators


## basic Imports functions

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
heart_dis_df = pd.read_csv("C:/Users/Safeer/Documents/MachineLearning/heart-disease.csv")

In [3]:
heart_dis_df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
#create X ( Feature Matrix)
X_data = heart_dis_df.drop('target', axis=1)

#creating Y ( Predection Matrix)
y = heart_dis_df['target']

In [5]:
X_data , y

(     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
 0     63    1   3       145   233    1        0      150      0      2.3   
 1     37    1   2       130   250    0        1      187      0      3.5   
 2     41    0   1       130   204    0        0      172      0      1.4   
 3     56    1   1       120   236    0        1      178      0      0.8   
 4     57    0   0       120   354    0        1      163      1      0.6   
 ..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
 298   57    0   0       140   241    0        1      123      1      0.2   
 299   45    1   3       110   264    0        1      132      0      1.2   
 300   68    1   0       144   193    1        1      141      0      3.4   
 301   57    1   0       130   131    0        1      115      1      1.2   
 302   57    0   1       130   236    0        0      174      0      0.0   
 
      slope  ca  thal  
 0        0   0     1  
 1        0   0     2  
 2

### chosing the models to classifey

In [6]:
clf = RandomForestClassifier ()

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [7]:
x_train, x_test, y_train, y_test = train_test_split(X_data,y, test_size=.2)
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
226   62    1   1       120   281    0        0      103      0      1.4   
264   54    1   0       110   206    0        0      108      1      0.0   
248   54    1   1       192   283    0        0      195      0      0.0   
254   59    1   3       160   273    0        0      125      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
284   61    1   0       140   207    0        0      138      1      1.9   
240   70    1   2       160   269    0        1      112      1      2.9   
276   58    1   0       146   218    0        1      105      0      2.0   
119   46    0   0       138   243    0        0      152      1      0.0   
260   66    0   0       178   228    1        1      165      1      1.0   

     slope  ca  thal  
179      1   1     1  
226      1   1     3  
264      1   1     2  
248      2   1     3  
254      2   0     2  
..     ...  ..   ...  
284      2   1     3  
240      1   1     3  
276      1   1     3  
119      1   0     2  
260      1   2     3  

[242 rows x 13 columns]

In [8]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [9]:
y_label = clf.predict(x_test)
y_label

array([0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1], dtype=int64)

In [10]:
clf.score(x_test, y_test)

0.7704918032786885

In [11]:
from  sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [12]:
print(classification_report(y_test, y_label))
print (confusion_matrix(y_test, y_label))
print (accuracy_score(y_test, y_label))

              precision    recall  f1-score   support

           0       0.73      0.79      0.76        28
           1       0.81      0.76      0.78        33

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61

[[22  6]
 [ 8 25]]
0.7704918032786885


# DATA PROCESSING

###CONVERTING DATA IN NUMERICAL FORMAT

In [2]:
car_sales  = pd.read_csv("C:/Users/Safeer/Documents/MachineLearning/car-sales-extended.csv")

In [14]:
car_sales

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [15]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

## making my custom sting to intiger convertor in car_sales dataframe

In [16]:
car_sales_make_keys = car_sales.Make.value_counts().keys()

In [17]:
cs_make_dic = dict()
for i in range(len(car_sales_make_keys)):
    cs_make_dic [car_sales_make_keys[i]] = i
    
cs_make_dic

{'Toyota': 0, 'Honda': 1, 'Nissan': 2, 'BMW': 3}

In [18]:
car_sales['Make'] = car_sales['Make'].replace(cs_make_dic, regex=True)
car_sales

Make Colour  Odometer (KM)  Doors  Price
0       1  White          35431      4  15323
1       3   Blue         192714      5  19943
2       1  White          84714      4  28343
3       0  White         154365      4  13434
4       2   Blue         181577      3  14043
..    ...    ...            ...    ...    ...
995     0  Black          35820      4  32042
996     2  White         155144      3   5716
997     2   Blue          66604      4  31570
998     1  White         215883      4   4001
999     0   Blue         248360      4  12732

[1000 rows x 5 columns]

In [19]:
car_sales.Colour.unique()

array(['White', 'Blue', 'Red', 'Green', 'Black'], dtype=object)

In [20]:
cs_colour_dic = dict()
car_sales_colours_keys = car_sales.Colour.unique()
for i in  range(len(car_sales_colours_keys)) :
    cs_colour_dic[car_sales_colours_keys[i]] = i

cs_colour_dic

{'White': 0, 'Blue': 1, 'Red': 2, 'Green': 3, 'Black': 4}

In [21]:
car_sales.Colour = car_sales.Colour.replace(cs_colour_dic, regex=True)
car_sales

Make  Colour  Odometer (KM)  Doors  Price
0       1       0          35431      4  15323
1       3       1         192714      5  19943
2       1       0          84714      4  28343
3       0       0         154365      4  13434
4       2       1         181577      3  14043
..    ...     ...            ...    ...    ...
995     0       4          35820      4  32042
996     2       0         155144      3   5716
997     2       1          66604      4  31570
998     1       0         215883      4   4001
999     0       1         248360      4  12732

[1000 rows x 5 columns]

In [22]:
car_sales.dtypes

Make             int64
Colour           int64
Odometer (KM)    int64
Doors            int64
Price            int64
dtype: object

In [23]:
# declaring the test and train data from car sale data frama
x = car_sales.drop('Price', axis=1)
y = car_sales.Price

In [24]:
x_train , x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

In [25]:
x_train

Make  Colour  Odometer (KM)  Doors
430     2       1          45668      4
877     0       0          14497      4
668     2       2         200403      4
252     1       1         228037      4
607     0       1         149270      4
..    ...     ...            ...    ...
754     3       0         168854      5
496     2       0         186752      4
161     3       1          86805      5
855     1       0         245327      4
593     1       1          68223      4

[800 rows x 4 columns]

In [26]:
y_train

430    13310
877    19838
668    15154
252     7076
607    21953
       ...  
754    23240
496     7882
161    34110
855     8226
593    27530
Name: Price, Length: 800, dtype: int64

In [27]:
clf1 = RandomForestClassifier ()

In [28]:
clf1.fit(x_train, y_train)

RandomForestClassifier()

In [29]:
y_predict = clf1.predict(x_test)
y_predict

array([31666,  6197, 12218,  9918, 25873, 13308, 17052, 12152, 17939,
       27640, 13251,  9263,  6174, 12152, 29140, 21830, 52458, 18346,
       18058, 19943, 17035,  8930, 10076,  8380, 22616, 14282, 19943,
        6197,  8179, 21236, 15962, 12547, 23719, 36864, 17690, 22489,
        8690, 22746, 16636, 12476,  8566, 17858, 17635, 21612,  5135,
        4165, 13427,  7183, 17690, 16001, 19408, 16337, 13928,  6720,
       20306, 10646, 31343, 32566,  9691, 12988,  8200,  8753, 22587,
       22794, 19106, 16337,  6075, 22825, 20155, 12988, 20867,  7183,
       35358, 15233, 16320, 12146, 15617, 28993, 11192, 21236, 15233,
        7097,  7061, 12152, 25649, 26078, 27598,  4239, 10628, 26926,
       11076,  7376, 23840, 16719, 24178,  8870,  8687, 15508,  4896,
       20242,  8089, 15095, 20142, 11210, 21188,  8738,  9649, 35600,
        8203, 20142, 19258,  5513, 35264, 14312, 10580, 20490, 10316,
        9780,  4022, 12402, 20242, 20237, 15372, 22542,  7994, 22436,
       14312,  8687,

In [30]:
clf1.score(x_test,y_test)

0.0

In [31]:
confusion_matrix(y_test, y_predict)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## applying one hot incoding to check the model working

In [32]:
car_sales  = pd.read_csv("C:/Users/Safeer/Documents/MachineLearning/car-sales-extended.csv")

In [33]:
dummy = pd.get_dummies (car_sales[["Colour","Make","Doors"]])
dummy

Doors  Colour_Black  Colour_Blue  Colour_Green  Colour_Red  Colour_White  \
0        4             0            0             0           0             1   
1        5             0            1             0           0             0   
2        4             0            0             0           0             1   
3        4             0            0             0           0             1   
4        3             0            1             0           0             0   
..     ...           ...          ...           ...         ...           ...   
995      4             1            0             0           0             0   
996      3             0            0             0           0             1   
997      4             0            1             0           0             0   
998      4             0            0             0           0             1   
999      4             0            1             0           0             0   

     Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  
0           0           1            0            0  
1           1           0            0            0  
2           0           1            0            0  
3           0           0            0            1  
4           0           0            1            0  
..        ...         ...          ...          ...  
995         0           0            0            1  
996         0           0            1            0  
997         0           0            1            0  
998         0           1            0            0  
999         0           0            0            1  

[1000 rows x 10 columns]

In [34]:
dummy["Odometer"] = car_sales["Odometer (KM)"]
dummy

Doors  Colour_Black  Colour_Blue  Colour_Green  Colour_Red  Colour_White  \
0        4             0            0             0           0             1   
1        5             0            1             0           0             0   
2        4             0            0             0           0             1   
3        4             0            0             0           0             1   
4        3             0            1             0           0             0   
..     ...           ...          ...           ...         ...           ...   
995      4             1            0             0           0             0   
996      3             0            0             0           0             1   
997      4             0            1             0           0             0   
998      4             0            0             0           0             1   
999      4             0            1             0           0             0   

     Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Odometer  
0           0           1            0            0     35431  
1           1           0            0            0    192714  
2           0           1            0            0     84714  
3           0           0            0            1    154365  
4           0           0            1            0    181577  
..        ...         ...          ...          ...       ...  
995         0           0            0            1     35820  
996         0           0            1            0    155144  
997         0           0            1            0     66604  
998         0           1            0            0    215883  
999         0           0            0            1    248360  

[1000 rows x 11 columns]

In [35]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(dummy,y, test_size= .2)

In [36]:
x_train1, y_train1

(     Doors  Colour_Black  Colour_Blue  Colour_Green  Colour_Red  Colour_White  \
 710      4             0            0             0           0             1   
 716      4             0            0             0           0             1   
 932      4             0            0             0           0             1   
 474      4             0            1             0           0             0   
 80       4             1            0             0           0             0   
 ..     ...           ...          ...           ...         ...           ...   
 738      4             0            1             0           0             0   
 211      4             0            0             0           0             1   
 750      4             0            0             1           0             0   
 261      4             0            0             0           0             1   
 839      4             0            1             0           0             0   
 
      Make_BMW

In [37]:
clf2 = RandomForestClassifier()

In [38]:
clf2.fit (x_train1,y_train1)

RandomForestClassifier()

In [39]:
y_label1 = clf2.predict(x_test1)

In [40]:
clf2.score(x_test1,y_test1)

0.0

### Applying sklearn hot incoding

In [3]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [4]:
categorical_feature = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()

transformer = ColumnTransformer ([
    ('one_hot',one_hot, categorical_feature)],
    remainder = 'passthrough'
)

transformer_x = transformer.fit_transform(car_sales)
transformer_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

In [10]:
car_trans_x = pd.DataFrame (transformer_x)
car_trans_x

0    1    2    3    4    5    6    7    8    9    10   11        12  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0   
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0   
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0   
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...   
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0   
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0   
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0   
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0   
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0   

          13  
0    15323.0  
1    19943.0  
2    28343.0  
3    13434.0  
4    14043.0  
..       ...  
995  32042.0  
996   5716.0  
997  31570.0  
998   4001.0  
999  12732.0  

[1000 rows x 14 columns]

In [11]:
car_trans_x = car_trans_x.drop (13, axis=1)
y = car_sales['Price']

In [7]:
car_trans_x

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [12]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(car_trans_x,y, test_size= .2)

In [13]:
clf3 = RandomForestClassifier()

In [14]:
clf3.fit(x_train1,y_train1)
y_label = clf3.predict(x_test1)
clf3.score (x_test1,y_test1)

0.0

In [16]:
clf3.score (x_train1,y_train1)

1.0

## Dealing with missing values

  1. One way to deal with missing values is to remove it from data frame. this will result in data loss and not sutable for small data sets.
  2. We can fill the missing values.
    
    . the missing values can be filled with mean values.
    
    . we can use a ML model to calculate the missing values.
    
    . we can make a bucket of data and fill that data with its corrosponding bucket.

In [18]:
#importing the missing values data frame

car_missing_df = pd.read_csv("C:/Users/Safeer/Documents/MachineLearning/car-sales-extended-missing-data.csv")

In [19]:
car_missing_df

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [29]:
car_missing_df.isnull().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [30]:
x_miss = car_missing_df.drop (columns='Price')
y_miss = car_missing_df['Price']

In [ ]:
catagorical_col = ['Make','Colour','Doors']
